authUser/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='auth'),
    path('login/',views.user_login,name='login'),
    path('signup/',views.signup,name='signup')
]

mypasswordmanager/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('passwordmanager.urls')),
    path('auth/',include('authUser.urls')),
]

passwordmanager/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('home/<str:username>',views.home,name='home'),
    path('addpassword',views.addPassword,name='addpassword'),
    path('',views.homepage,name='homepage')

]

authUser/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User

# Create your models here.
class passwordUser(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.username

passwordmanager/models.py
from django.db import models
from authUser.models import passwordUser
# Create your models here.
class Password(models.Model):
    websiteName=models.CharField(max_length=500)
    password=models.CharField(max_length=50)
    passworduser=models.ForeignKey(passwordUser,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.websiteName

authUser/views.py
from django.shortcuts import render,HttpResponse,redirect

# Create your views here.
def index(request):
    return HttpResponse("auth")

from django.core.checks import messages
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User
from django.urls import reverse
from .models import passwordUser
from django.contrib.auth.decorators import login_required 
# Create your views here.
def user_login(request):
    if request.method=="GET":
        return render(request,"login.html")
        
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        user=authenticate(username=username,password=password)
        print(user)
        if user is not None:
            login(request,user)
            return redirect('home',user.username)
        else:
            # messages.error(request,'Password donot match')
            return redirect('login')
    
    



def signup(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        cpassword=request.POST.get("cpassword")
        if password==cpassword:
            if len(password)>=8 and len(cpassword)>=8:
                print("password matched")
                if User.objects.filter(username=username).exists():
                    messages.Error(request,"Username or password is invalid")
                    
                    return redirect('signup')
                else:
                    
                    user=User.objects.create_user(username=username,password=cpassword)
                    passwordUser.objects.create(user=user)
                    return redirect('login')
            else:
                
                print("password donot match")
                messages.Error(request,"Password must be atleast 8 characters")
                return redirect('signup')

        else:
            messages.Error(request,"Password donot match")
            return redirect('signup')

    return render(request,"signup.html")


# @login_required
# def logout_view(request):
#     logout(request)
#     return redirect("login")

passwordmanager/views.py
from django.shortcuts import render,HttpResponseRedirect
from .models import Password,passwordUser
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.urls import reverse




#form

class PasswordForm(forms.ModelForm):

    class Meta:
        model=Password
        fields=["websiteName","password"]
        widgets={
            "websiteName":forms.TextInput(attrs={"class":"form-control"}),
            "password":forms.TextInput(attrs={"class":"form-control"}),
        }




@login_required
def home(request,username):
    Passwords=passwordUser.objects.get(user=User.objects.get(username=username))
    context={
        'passwords':Passwords,
    }
    
    return render(request,"home.html",context)
    



def addPassword(request):
    
    
        form=PasswordForm(request.POST or None)
        if request.method=="POST":
            if form.is_valid():
                form.cleaned_data["passworduser"]=request.user.passworduser
                Password.objects.create(**form.cleaned_data)
                
        context={
            "form":form
            
            }
        return render(request,"addpassword.html",context)
def homepage(request):
    return render(request,"homepage.html")

templates/addpassword.html
{% extends 'master/base.html' %}
{% block body %}

<div class="container">
    <form  action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-success"type="submit">Submit</button>
    </form>

</div>

{% endblock body %}

templates/home.html
{% extends 'master/base.html' %} {% block body %}
<div class="container">

<div class="container">
    {% comment %} <h1><a href="{% url 'index' %}">Home</a></h1> {% endcomment %}
  <h1>Your Passwords</h1>
  
  <table class="table">
  <thead>
    <tr>
      <th scope="col">No</th>
      <th scope="col">Website Name</th>
      <th scope="col">Password</th>
    </tr>
  </thead>
  <tbody>
  {% for password in passwords.password_set.all %}
    
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{password}}</td>
      <td>{{password.password}}</td>
      
    </tr> 
    
    
    {% endfor %}
    
  </tbody>
</table>
</div>

{%endblock%}

templates/homepage.html
{% extends 'master/base.html' %} {% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <a href="{%url 'login' %}"  class="btn btn-outline-success">Login</a>
        </div>
        <div class="col-md-6">
            <a href="{%url 'signup' %}"  class="btn btn-outline-success">Signup</a>
        </div>
    </div>

</div>

{%endblock%}

templates/login.html
{% extends 'master/base.html' %} 
{% block body %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Signin</title>
  </head>
  
  <body class="text-center">
  <div class="container">
    <form class="form-signin" method="POST">
      {%csrf_token%}
      
      <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
      <label for="inputText" class="sr-only">Username</label>
      <input type="text" id="inputEmail" class="form-control" placeholder="Username" name="username">
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">
      
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
    </div>
  </body>
</html>


{%endblock%}

templates/master/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Password Manager</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>

        {%if request.user.is_authenticated%}
          <li class="nav-item">
          <a class="nav-link" href={%url 'addpassword'%}>Add Password</a>

          <li class="nav-item">
          <a class="nav-link" href={%url 'home' request.user.username%}>My password</a>
        </li>
        {% endif %}
       
    </div>
  </div>
</nav>
    {% block body %}
    
    
    {% endblock body %}

   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

   
  </body>
</html>

templates/signup.html
{% extends 'master/base.html' %} 
{% block body %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>SignUp</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">


  </head>

  <body class="text-center mt-5">
      {% if messages %}
      <ul class="messages">
      {% for message in messages %}
      <li {% if message.level == DEFAULT_MESSAGE_LEVEL.ERROR %}Important:{% endif %}
      {{message}}
      </li>
      
      
      
      {% endfor %}
      
      
      
      </ul>
      
      
      {% endif %}
    <form class="form-signin" method="POST">
        {%csrf_token%}
      
      <h1 class="h3 mb-3 font-weight-normal">Please signup</h1>
      
      <input type="text" id="inputEmail" class="form-control" placeholder="Username" required name="username">
     
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">
      
      <input type="password" id="inputPassword" class="form-control" placeholder="Confirm Password" required name="cpassword">
      
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
    </form>
  </body>
</html>


{%endblock%}